baseURL = 'https://xisle.net/'
languageCode = 'en-us'
title = 'X/Isle'
theme = "xisle"

[module]
  [[module.mounts]]
    disableWatch = false
    lang = ''
    source = '../_content'
    target = 'content'

[mediaTypes]
[mediaTypes."application/geojson"]
  suffixes = ["json"]

[outputFormats]
  [outputFormats.geojson]
    baseName = "locations"
    isPlainText = true
    mediaType = "application/geojson"

[outputs]
  home = ['html', 'rss', 'json', 'geojson']
  page = ['html', 'json', 'geojson']  
  section = ['html', 'rss', 'json', 'geojson']