media:
  - name: files
    label: Files
    input: _content/documents
    output: /documents
    categories: [ document ]
  - name: images # Note: 'name' key is required here
    label: Images
    input: _content/images
    output: /images
    extensions: [ png, webp, jpg, jpeg ]
components:
  location: # 'hero' is the component name/key
    label: Location
    type: object
    fields:
      - name: latitude
        label: Latitude
        type: number
      - name: longitude
        label: Longitude
        type: number
      - name: elevation
        label: Elevation
        type: number
  view:
    label: View
    type: object
    fields:
      - name: latitude
        label: Latitude
        type: number
      - name: longitude
        label: Longitude
        type: number
      - name: height
        label: Height
        type: number
      - name: heading
        label: Heading
        type: number
      - name: pitch
        label: Pitch
        type: number
      - name: roll
        label: Roll
        type: number
         
  email: # 'email' is the component name/key
    label: Email Address
    type: string
    pattern:
      regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
      message: 'This must be a valid email address (e.g. hello@example.com).'
content:
  - name: areas
    label: Areas
    type: collection
    path: '_content/areas'
    filename: '{primary}.md'
    view:
      fields: [ title, published, date ]
    fields:
      - name: thumb
        label: Thumbnail
        type: image
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: published
        label: Published
        type: date
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: location
        component: location
      - name: view
        component: view
      - name: body
        label: Body
        type: rich-text
        options:
          media: images
          extensions: ['png', 'jpg', 'jpeg']
      - name: dangers
        label: Dangers
        type: rich-text
        options:
          media: images
          extensions: ['png']

  - name: pins
    label: Pins
    path: _content/pins
    filename: '{primary}.md'
    type: collection
    fields:
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: json
        label: Location/View
        type: string
      - name: published
        label: Published
        type: date
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: location
        component: location
      - name: areas
        label: Areas
        type: reference
        options:
          collection: areas
          multiple: true
      - name: body
        label: Body
        type: rich-text
        
