name = "xisle" # Replace with a unique name for your Worker
compatibility_date = "2024-06-23" # Use the current date or a recent one
# This is the crucial part for static assets
[assets]
directory = "_hugo-output"
not_found_handling = "404-page"

# CF API Token     JGwEYWgTadxN_I761rDMT36q7R7eX1net2YxOL7N