name: Deploy to Cloudflare Workers Sites

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1 # Use the latest version

      - name: Install dependencies (with Bun)
        run: bun install
        
      - name: Setup Latest Version of Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo Site
        run: hugo --destination ./_output --source hugo --minify --gc

      - name: Publish to Cloudflare Workers Sites
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
