name: Deploy to Cloudflare Workers Sites

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Setup Latest Version of Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: install tailwindcli
        run:
          TAILWIND_CLI_VERSION="v4.1.11"

          INSTALL_DIR="${{ runner.temp }}/tailwindcss-cli" 

          mkdir -p "$INSTALL_DIR"

          if [ "${{ runner.os }}" == "Linux" ]; then

            CLI_ARCH="linux-x64"

          elif [ "${{ runner.os }}" == "macOS" ]; then

            CLI_ARCH="macos-x64"

          elif [ "${{ runner.os }}" == "Windows" ]; then

            CLI_ARCH="windows-x64"

          else

            echo "Unsupported runner OS"

            exit 1

          fi

          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/${TAILWIND_CLI_VERSION}/tailwindcss-${CLI_ARCH}

          chmod +x tailwindcss-${CLI_ARCH}

          mv tailwindcss-${CLI_ARCH} "$INSTALL_DIR/tailwindcss"

          echo "$INSTALL_DIR" >> $GITHUB_PATH # Add the directory to PATH for subsequent steps

      - name: Build Hugo Site
        run: hugo config mounts --source hugo-site
        env:
          HUGO_ENV: production
  
 
      - name: List Assets Directory
        run: |
          echo "Listing contents of assets/ folder:"
          ls -R .
          echo "--- End assets listing ---"          

      - name: Build Hugo Site
        run: |
          cd hugo-site
          hugo --destination ../_hugo-output --minify --gc --logLevel debug
        env:
          HUGO_ENV: production
          
      - name: List Assets Directory
        run: |
          echo "Listing contents of assets/ folder:"
          ls -R ./_cms/assets/media
          echo "--- End assets listing ---"      
      
      - name: t
        run: |
          cat ./_hugo-output/areas/dallas-road/index.html
          
      - name: dir
        run: ls

      - name: Publish to Cloudflare Workers Sites
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
